version: '3'
services:
  app:
    env_file:
      - .env
    build: .
    expose:
      - 8000
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
       - ${DUMP_DIR}:/tmp/dumps
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data: