version: '3'
services:
#  app:
#    env_file:
#      - .env
#    build: .
#    expose:
#      - 8000
#    ports:
#      - "8080:8000"
#    volumes:
#      - .:/app
#    depends_on:
#      - db
  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
       - "pg_data:/var/lib/postgresql/data"
       - ${DUMP_DIR}:/tmp/dumps

  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  pg_data: