"""add steps

Revision ID: 08d74f194595
Revises: 8dc5b592462e
Create Date: 2023-12-04 02:15:44.911249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d74f194595'
down_revision: Union[str, None] = '8dc5b592462e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('lesson_step', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('question_step', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_step')
    op.drop_column('lessons', 'lesson_step')
    # ### end Alembic commands ###
