"""add next_state

Revision ID: b30cfcd2240d
Revises: 08d74f194595
Create Date: 2023-12-04 03:22:54.891187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30cfcd2240d'
down_revision: Union[str, None] = '08d74f194595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('next_step', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('next_step', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'next_step')
    op.drop_column('lessons', 'next_step')
    # ### end Alembic commands ###
