"""add seconds in Lessons

Revision ID: 8dc5b592462e
Revises: 59f64af975da
Create Date: 2023-11-13 00:34:41.005809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc5b592462e'
down_revision: Union[str, None] = '59f64af975da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('next_lesson_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'next_lesson_duration')
    op.drop_column('lessons', 'keywords')
    op.drop_column('lessons', 'description')
    # ### end Alembic commands ###
