"""add message

Revision ID: 370ed17ef4f5
Revises: b30cfcd2240d
Create Date: 2024-01-22 17:38:29.261163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370ed17ef4f5'
down_revision: Union[str, None] = 'b30cfcd2240d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('button_action_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('button_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('message_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attachment_type_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.String(length=255), nullable=True),
    sa.Column('message_group_id', sa.Integer(), nullable=True),
    sa.Column('id_in_group', sa.Integer(), nullable=True),
    sa.Column('start_message', sa.Boolean(), nullable=True),
    sa.Column('message_type_id', sa.Integer(), nullable=True),
    sa.Column('next_messages', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['attachment_type_id'], ['attachment_type.id'], ),
    sa.ForeignKeyConstraint(['message_group_id'], ['message_group.id'], ),
    sa.ForeignKeyConstraint(['message_type_id'], ['message_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_button',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('button_type_id', sa.Integer(), nullable=True),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('button_action', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['button_action_type.id'], ),
    sa.ForeignKeyConstraint(['button_type_id'], ['button_type.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('variable_for_comparison', sa.String(length=255), nullable=True),
    sa.Column('delay_before_send', sa.Integer(), nullable=True),
    sa.Column('variable_to_save', sa.String(length=255), nullable=True),
    sa.Column('message_from_id', sa.Integer(), nullable=True),
    sa.Column('message_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_from_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['message_to_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tg_users', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_users', 'extra_data')
    op.drop_table('message_condition')
    op.drop_table('message_button')
    op.drop_table('message')
    op.drop_table('message_type')
    op.drop_table('message_group')
    op.drop_table('button_type')
    op.drop_table('button_action_type')
    op.drop_table('attachment_type')
    # ### end Alembic commands ###
