"""Create user_directory table

Revision ID: 1ab9fbe7149e
Revises: e21c7929b3b4
Create Date: 2024-09-01 23:08:10.101246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab9fbe7149e'
down_revision: Union[str, None] = 'e21c7929b3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_directory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_directory')
    # ### end Alembic commands ###
