"""add seminar id and question_number

Revision ID: e21c7929b3b4
Revises: 286eb0804f7d
Create Date: 2024-03-24 14:04:57.714343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21c7929b3b4'
down_revision: Union[str, None] = '286eb0804f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('seminar', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('question_number', sa.Integer(), nullable=True))
    op.add_column('message_condition', sa.Column('question_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'seminar')
    op.drop_column('questions', 'question_number')
    op.drop_column('message_condition', 'question_number')
    # ### end Alembic commands ###
