"""true empty message

Revision ID: ba2d2555b7f3
Revises: 0c0d14d1d168
Create Date: 2024-02-08 00:13:26.064604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2d2555b7f3'
down_revision: Union[str, None] = '0c0d14d1d168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_log', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_log', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
