"""questions new

Revision ID: 4ff139e52099
Revises: e91887eae42f
Create Date: 2024-02-05 20:43:57.477941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff139e52099'
down_revision: Union[str, None] = 'e91887eae42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_condition', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message_condition', 'questions', ['question_id'], ['id'])
    op.add_column('questions', sa.Column('next_question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'questions', ['next_question_id'], ['id'])
    op.drop_column('questions', 'question_step')
    op.drop_column('questions', 'name')
    op.drop_column('questions', 'body')
    op.drop_column('questions', 'next_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('next_step', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('question_step', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'next_question_id')
    op.drop_constraint(None, 'message_condition', type_='foreignkey')
    op.drop_column('message_condition', 'question_id')
    # ### end Alembic commands ###
