"""add logs

Revision ID: 0c0d14d1d168
Revises: 4ff139e52099
Create Date: 2024-02-07 00:27:32.889317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0d14d1d168'
down_revision: Union[str, None] = '4ff139e52099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_message_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'text')
    op.drop_table('message_log')
    # ### end Alembic commands ###
