"""add mailing table

Revision ID: cffe98d081af
Revises: 550cf6b35d0d
Create Date: 2024-02-11 01:46:28.104094

"""
from typing import Sequence, Union

from alembic import op
from models import MailingStatus
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'cffe98d081af'
down_revision: Union[str, None] = '550cf6b35d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(
        MailingStatus, impl=sa.Integer()
    ), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('begin_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['tg_users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing')
    # ### end Alembic commands ###
