"""alter column messageName

Revision ID: 286eb0804f7d
Revises: 0476989c4b85
Create Date: 2024-02-27 15:54:19.194989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286eb0804f7d'
down_revision: Union[str, None] = '0476989c4b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.Text(),
                    existing_nullable=True)
    op.alter_column('message_condition', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'name',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('message_condition', 'name',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
